-- CreateEnum
CREATE TYPE "CustomerSegment" AS ENUM ('A1_SOLO_MARKA', 'A2_KENDI_ZINCIRI', 'A3_FRANCHISE_ALAN', 'A4_FRANCHISE_ALAN_TEDARIK_ZORUNLU', 'A5_FRANCHISE_VEREN', 'A6_FRANCHISE_VEREN_TEDARIK_ZORUNLU');

-- AlterTable
ALTER TABLE "tenants" ADD COLUMN "customerSegment" "CustomerSegment";
