import { LeasesService } from './leases.service';
import { CreateLeaseDto } from './dto/create-lease.dto';
import { UpdateLeaseDto } from './dto/update-lease.dto';
export declare class LeasesController {
    private readonly leasesService;
    constructor(leasesService: LeasesService);
    findAll(user: any, filters: any): Promise<({
        store: {
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.StoreStatus;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string;
            brand: string | null;
            concept: string | null;
            country: string;
            city: string;
            district: string | null;
            address: string;
            squareMeters: number;
            openingDate: Date | null;
            mallId: string | null;
            closingDate: Date | null;
        };
        mall: {
            type: import(".prisma/client").$Enums.MallType;
            tenantId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            country: string;
            city: string;
            district: string | null;
            address: string;
            managementCompany: string | null;
            relationshipQuality: import(".prisma/client").$Enums.RelationshipQuality;
        };
        assignedTo: {
            email: string;
            firstName: string;
            lastName: string;
            id: string;
        };
    } & {
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.LeaseStatus;
        createdAt: Date;
        updatedAt: Date;
        currency: string;
        mallId: string | null;
        storeId: string;
        assignedToId: string | null;
        contractNumber: string;
        version: number;
        startDate: Date;
        endDate: Date;
        signedDate: Date | null;
        monthlyRent: number;
        escalationType: import(".prisma/client").$Enums.EscalationType;
        escalationRate: number;
        escalationIndex: string | null;
        renewalOptionMonths: number | null;
        renewalNoticeMonths: number;
        commonAreaCharges: number | null;
        securityDeposit: number | null;
        fitOutPeriodDays: number | null;
        documentUrl: string | null;
        documentVersion: number;
    })[]>;
    findExpiring(user: any, days?: number): Promise<({
        store: {
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.StoreStatus;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string;
            brand: string | null;
            concept: string | null;
            country: string;
            city: string;
            district: string | null;
            address: string;
            squareMeters: number;
            openingDate: Date | null;
            mallId: string | null;
            closingDate: Date | null;
        };
        mall: {
            type: import(".prisma/client").$Enums.MallType;
            tenantId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            country: string;
            city: string;
            district: string | null;
            address: string;
            managementCompany: string | null;
            relationshipQuality: import(".prisma/client").$Enums.RelationshipQuality;
        };
    } & {
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.LeaseStatus;
        createdAt: Date;
        updatedAt: Date;
        currency: string;
        mallId: string | null;
        storeId: string;
        assignedToId: string | null;
        contractNumber: string;
        version: number;
        startDate: Date;
        endDate: Date;
        signedDate: Date | null;
        monthlyRent: number;
        escalationType: import(".prisma/client").$Enums.EscalationType;
        escalationRate: number;
        escalationIndex: string | null;
        renewalOptionMonths: number | null;
        renewalNoticeMonths: number;
        commonAreaCharges: number | null;
        securityDeposit: number | null;
        fitOutPeriodDays: number | null;
        documentUrl: string | null;
        documentVersion: number;
    })[]>;
    findOne(id: string, user: any): Promise<{
        daysRemaining: number;
        isExpiringSoon: boolean;
        store: {
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.StoreStatus;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string;
            brand: string | null;
            concept: string | null;
            country: string;
            city: string;
            district: string | null;
            address: string;
            squareMeters: number;
            openingDate: Date | null;
            mallId: string | null;
            closingDate: Date | null;
        };
        mall: {
            type: import(".prisma/client").$Enums.MallType;
            tenantId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            country: string;
            city: string;
            district: string | null;
            address: string;
            managementCompany: string | null;
            relationshipQuality: import(".prisma/client").$Enums.RelationshipQuality;
        };
        assignedTo: {
            email: string;
            firstName: string;
            lastName: string;
            id: string;
        };
        renewals: {
            id: string;
            status: import(".prisma/client").$Enums.RenewalStatus;
            createdAt: Date;
            updatedAt: Date;
            leaseId: string;
            proposedMonthlyRent: number | null;
            proposedDuration: number | null;
            proposedStartDate: Date | null;
            landlordResponse: string | null;
            notes: string | null;
            reminderSentAt: Date | null;
            negotiationStartDate: Date | null;
            completionDate: Date | null;
        }[];
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.LeaseStatus;
        createdAt: Date;
        updatedAt: Date;
        currency: string;
        mallId: string | null;
        storeId: string;
        assignedToId: string | null;
        contractNumber: string;
        version: number;
        startDate: Date;
        endDate: Date;
        signedDate: Date | null;
        monthlyRent: number;
        escalationType: import(".prisma/client").$Enums.EscalationType;
        escalationRate: number;
        escalationIndex: string | null;
        renewalOptionMonths: number | null;
        renewalNoticeMonths: number;
        commonAreaCharges: number | null;
        securityDeposit: number | null;
        fitOutPeriodDays: number | null;
        documentUrl: string | null;
        documentVersion: number;
    }>;
    getCurrentRent(id: string, user: any): Promise<{
        leaseId: string;
        baseRent: number;
        currentRent: number;
        yearsElapsed: number;
        escalationType: import(".prisma/client").$Enums.EscalationType;
        escalationRate: number;
    }>;
    create(user: any, createDto: CreateLeaseDto): Promise<{
        store: {
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.StoreStatus;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string;
            brand: string | null;
            concept: string | null;
            country: string;
            city: string;
            district: string | null;
            address: string;
            squareMeters: number;
            openingDate: Date | null;
            mallId: string | null;
            closingDate: Date | null;
        };
        mall: {
            type: import(".prisma/client").$Enums.MallType;
            tenantId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            country: string;
            city: string;
            district: string | null;
            address: string;
            managementCompany: string | null;
            relationshipQuality: import(".prisma/client").$Enums.RelationshipQuality;
        };
    } & {
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.LeaseStatus;
        createdAt: Date;
        updatedAt: Date;
        currency: string;
        mallId: string | null;
        storeId: string;
        assignedToId: string | null;
        contractNumber: string;
        version: number;
        startDate: Date;
        endDate: Date;
        signedDate: Date | null;
        monthlyRent: number;
        escalationType: import(".prisma/client").$Enums.EscalationType;
        escalationRate: number;
        escalationIndex: string | null;
        renewalOptionMonths: number | null;
        renewalNoticeMonths: number;
        commonAreaCharges: number | null;
        securityDeposit: number | null;
        fitOutPeriodDays: number | null;
        documentUrl: string | null;
        documentVersion: number;
    }>;
    update(id: string, user: any, updateDto: UpdateLeaseDto): Promise<{
        store: {
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.StoreStatus;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string;
            brand: string | null;
            concept: string | null;
            country: string;
            city: string;
            district: string | null;
            address: string;
            squareMeters: number;
            openingDate: Date | null;
            mallId: string | null;
            closingDate: Date | null;
        };
        mall: {
            type: import(".prisma/client").$Enums.MallType;
            tenantId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            country: string;
            city: string;
            district: string | null;
            address: string;
            managementCompany: string | null;
            relationshipQuality: import(".prisma/client").$Enums.RelationshipQuality;
        };
    } & {
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.LeaseStatus;
        createdAt: Date;
        updatedAt: Date;
        currency: string;
        mallId: string | null;
        storeId: string;
        assignedToId: string | null;
        contractNumber: string;
        version: number;
        startDate: Date;
        endDate: Date;
        signedDate: Date | null;
        monthlyRent: number;
        escalationType: import(".prisma/client").$Enums.EscalationType;
        escalationRate: number;
        escalationIndex: string | null;
        renewalOptionMonths: number | null;
        renewalNoticeMonths: number;
        commonAreaCharges: number | null;
        securityDeposit: number | null;
        fitOutPeriodDays: number | null;
        documentUrl: string | null;
        documentVersion: number;
    }>;
    renew(id: string, user: any): Promise<{
        id: string;
        status: import(".prisma/client").$Enums.RenewalStatus;
        createdAt: Date;
        updatedAt: Date;
        leaseId: string;
        proposedMonthlyRent: number | null;
        proposedDuration: number | null;
        proposedStartDate: Date | null;
        landlordResponse: string | null;
        notes: string | null;
        reminderSentAt: Date | null;
        negotiationStartDate: Date | null;
        completionDate: Date | null;
    }>;
}
//# sourceMappingURL=leases.controller.d.ts.map