import { MallsService } from './malls.service';
export declare class MallsController {
    private readonly mallsService;
    constructor(mallsService: MallsService);
    findAll(): Promise<({
        stores: {
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.StoreStatus;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string;
            brand: string | null;
            concept: string | null;
            country: string;
            city: string;
            district: string | null;
            address: string;
            squareMeters: number;
            openingDate: Date | null;
            mallId: string | null;
            closingDate: Date | null;
        }[];
        contacts: {
            title: string | null;
            email: string | null;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            mallId: string;
            phone: string | null;
            isPrimary: boolean;
        }[];
    } & {
        type: import(".prisma/client").$Enums.MallType;
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        country: string;
        city: string;
        district: string | null;
        address: string;
        managementCompany: string | null;
        relationshipQuality: import(".prisma/client").$Enums.RelationshipQuality;
    })[]>;
    findOne(id: string): Promise<{
        negotiations: {
            description: string | null;
            type: import(".prisma/client").$Enums.NegotiationType;
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.NegotiationStatus;
            createdAt: Date;
            updatedAt: Date;
            mallId: string;
            startDate: Date;
            endDate: Date | null;
            leaseId: string | null;
            userId: string;
            subject: string;
            outcome: string | null;
            agreedTerms: string | null;
            nextFollowUp: Date | null;
        }[];
        stores: {
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.StoreStatus;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string;
            brand: string | null;
            concept: string | null;
            country: string;
            city: string;
            district: string | null;
            address: string;
            squareMeters: number;
            openingDate: Date | null;
            mallId: string | null;
            closingDate: Date | null;
        }[];
        leases: {
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.LeaseStatus;
            createdAt: Date;
            updatedAt: Date;
            currency: string;
            mallId: string | null;
            storeId: string;
            assignedToId: string | null;
            contractNumber: string;
            version: number;
            startDate: Date;
            endDate: Date;
            signedDate: Date | null;
            monthlyRent: number;
            escalationType: import(".prisma/client").$Enums.EscalationType;
            escalationRate: number;
            escalationIndex: string | null;
            renewalOptionMonths: number | null;
            renewalNoticeMonths: number;
            commonAreaCharges: number | null;
            securityDeposit: number | null;
            fitOutPeriodDays: number | null;
            documentUrl: string | null;
            documentVersion: number;
        }[];
        contacts: {
            title: string | null;
            email: string | null;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            mallId: string;
            phone: string | null;
            isPrimary: boolean;
        }[];
    } & {
        type: import(".prisma/client").$Enums.MallType;
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        country: string;
        city: string;
        district: string | null;
        address: string;
        managementCompany: string | null;
        relationshipQuality: import(".prisma/client").$Enums.RelationshipQuality;
    }>;
    create(createDto: any): Promise<{
        type: import(".prisma/client").$Enums.MallType;
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        country: string;
        city: string;
        district: string | null;
        address: string;
        managementCompany: string | null;
        relationshipQuality: import(".prisma/client").$Enums.RelationshipQuality;
    }>;
    updateRelationship(id: string, body: {
        quality: string;
    }): Promise<{
        type: import(".prisma/client").$Enums.MallType;
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        country: string;
        city: string;
        district: string | null;
        address: string;
        managementCompany: string | null;
        relationshipQuality: import(".prisma/client").$Enums.RelationshipQuality;
    }>;
}
//# sourceMappingURL=malls.controller.d.ts.map