import { PrismaService } from '../../database/prisma.service';
import { CreateFranchiseProjectDto } from './dto/create-franchise-project.dto';
import { UpdateFranchiseProjectDto } from './dto/update-franchise-project.dto';
export declare class FranchiseProjectsService {
    private prisma;
    constructor(prisma: PrismaService);
    findAll(tenantId: string, filters?: any): Promise<({
        tasks: {
            description: string | null;
            title: string;
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.TaskStatus;
            createdAt: Date;
            updatedAt: Date;
            mallId: string | null;
            storeId: string | null;
            assignedToId: string | null;
            leaseId: string | null;
            category: import(".prisma/client").$Enums.LeasingTaskCategory;
            priority: import(".prisma/client").$Enums.TaskPriority;
            franchiseProjectId: string | null;
            defaultSLA: number | null;
            riskLevel: import(".prisma/client").$Enums.RiskLevel;
            dueDate: Date | null;
            completedAt: Date | null;
        }[];
    } & {
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.FranchiseProjectStatus;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        code: string | null;
        brand: string | null;
        concept: string | null;
        storeId: string | null;
        notes: string | null;
        targetRegion: string | null;
        targetCity: string | null;
        targetMallId: string | null;
        storeType: string | null;
        estimatedCapex: number | null;
        estimatedOpex: number | null;
        expectedRevenue: number | null;
        expectedRentCost: number | null;
        feasibilityScore: number | null;
        riskAssessment: string | null;
        projectManagerId: string | null;
        targetOpeningDate: Date | null;
        actualOpeningDate: Date | null;
    })[]>;
    findOne(id: string, tenantId: string): Promise<{
        tasks: {
            description: string | null;
            title: string;
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.TaskStatus;
            createdAt: Date;
            updatedAt: Date;
            mallId: string | null;
            storeId: string | null;
            assignedToId: string | null;
            leaseId: string | null;
            category: import(".prisma/client").$Enums.LeasingTaskCategory;
            priority: import(".prisma/client").$Enums.TaskPriority;
            franchiseProjectId: string | null;
            defaultSLA: number | null;
            riskLevel: import(".prisma/client").$Enums.RiskLevel;
            dueDate: Date | null;
            completedAt: Date | null;
        }[];
    } & {
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.FranchiseProjectStatus;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        code: string | null;
        brand: string | null;
        concept: string | null;
        storeId: string | null;
        notes: string | null;
        targetRegion: string | null;
        targetCity: string | null;
        targetMallId: string | null;
        storeType: string | null;
        estimatedCapex: number | null;
        estimatedOpex: number | null;
        expectedRevenue: number | null;
        expectedRentCost: number | null;
        feasibilityScore: number | null;
        riskAssessment: string | null;
        projectManagerId: string | null;
        targetOpeningDate: Date | null;
        actualOpeningDate: Date | null;
    }>;
    create(tenantId: string, createDto: CreateFranchiseProjectDto): Promise<{
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.FranchiseProjectStatus;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        code: string | null;
        brand: string | null;
        concept: string | null;
        storeId: string | null;
        notes: string | null;
        targetRegion: string | null;
        targetCity: string | null;
        targetMallId: string | null;
        storeType: string | null;
        estimatedCapex: number | null;
        estimatedOpex: number | null;
        expectedRevenue: number | null;
        expectedRentCost: number | null;
        feasibilityScore: number | null;
        riskAssessment: string | null;
        projectManagerId: string | null;
        targetOpeningDate: Date | null;
        actualOpeningDate: Date | null;
    }>;
    update(id: string, tenantId: string, updateDto: UpdateFranchiseProjectDto): Promise<{
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.FranchiseProjectStatus;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        code: string | null;
        brand: string | null;
        concept: string | null;
        storeId: string | null;
        notes: string | null;
        targetRegion: string | null;
        targetCity: string | null;
        targetMallId: string | null;
        storeType: string | null;
        estimatedCapex: number | null;
        estimatedOpex: number | null;
        expectedRevenue: number | null;
        expectedRentCost: number | null;
        feasibilityScore: number | null;
        riskAssessment: string | null;
        projectManagerId: string | null;
        targetOpeningDate: Date | null;
        actualOpeningDate: Date | null;
    }>;
    remove(id: string, tenantId: string): Promise<{
        success: boolean;
        message: string;
    }>;
    getStatistics(tenantId: string): Promise<{
        total: number;
        pipeline: number;
        evaluation: number;
        approved: number;
        opened: number;
        byCity: {
            city: string;
            count: unknown;
        }[];
        avgFeasibilityScore: number;
    }>;
    private getProjectsByCity;
    private getAvgFeasibilityScore;
}
//# sourceMappingURL=franchise-projects.service.d.ts.map