import { PrismaService } from '../../database/prisma.service';
import { CreateJobDescriptionDto } from './dto/create-job-description.dto';
export declare class JobDescriptionsService {
    private prisma;
    constructor(prisma: PrismaService);
    findAll(tenantId: string, filters?: any): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }[]>;
    findOne(id: string, tenantId: string): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }>;
    create(tenantId: string, userId: string, createDto: CreateJobDescriptionDto): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }>;
    update(id: string, tenantId: string, updateDto: Partial<CreateJobDescriptionDto>): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }>;
    remove(id: string, tenantId: string): Promise<{
        success: boolean;
        message: string;
    }>;
    publish(id: string, tenantId: string): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }>;
    unpublish(id: string, tenantId: string): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }>;
    exportToPosting(id: string, tenantId: string, language?: 'TR' | 'EN'): Promise<string>;
    private formatJobPostingTR;
    private formatJobPostingEN;
    getDefaultLeasingManagerTemplate(): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        nameTR: string;
        nameEN: string;
        descriptionTR: string | null;
        descriptionEN: string | null;
        coreResponsibilities: string[];
        coreSkills: string[];
        isDefault: boolean;
        isActive: boolean;
    }>;
    generateFromLeasingManagerTemplate(tenantId: string, userId: string, companyContext?: any): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }>;
}
//# sourceMappingURL=job-descriptions.service.d.ts.map