import { LeasingTasksService } from './leasing-tasks.service';
import { FranchiseProjectsService } from './franchise-projects.service';
import { LeasingRequestsService } from './leasing-requests.service';
import { JobDescriptionsService } from './job-descriptions.service';
import { CreateLeasingTaskDto } from './dto/create-leasing-task.dto';
import { UpdateLeasingTaskDto } from './dto/update-leasing-task.dto';
import { CreateFranchiseProjectDto } from './dto/create-franchise-project.dto';
import { UpdateFranchiseProjectDto } from './dto/update-franchise-project.dto';
import { CreateLeasingRequestDto } from './dto/create-leasing-request.dto';
import { UpdateLeasingRequestDto } from './dto/update-leasing-request.dto';
import { CreateJobDescriptionDto } from './dto/create-job-description.dto';
export declare class LeasingManagerController {
    private readonly leasingTasksService;
    private readonly franchiseProjectsService;
    private readonly leasingRequestsService;
    private readonly jobDescriptionsService;
    constructor(leasingTasksService: LeasingTasksService, franchiseProjectsService: FranchiseProjectsService, leasingRequestsService: LeasingRequestsService, jobDescriptionsService: JobDescriptionsService);
    findAllTasks(req: any, filters: any): Promise<{
        description: string | null;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.TaskStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        category: import(".prisma/client").$Enums.LeasingTaskCategory;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        defaultSLA: number | null;
        riskLevel: import(".prisma/client").$Enums.RiskLevel;
        dueDate: Date | null;
        completedAt: Date | null;
    }[]>;
    getTaskStatistics(req: any): Promise<{
        total: number;
        pending: number;
        inProgress: number;
        completed: number;
        byCategory: {
            category: string;
            count: unknown;
        }[];
        byPriority: {
            priority: string;
            count: unknown;
        }[];
    }>;
    findOneTask(id: string, req: any): Promise<{
        description: string | null;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.TaskStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        category: import(".prisma/client").$Enums.LeasingTaskCategory;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        defaultSLA: number | null;
        riskLevel: import(".prisma/client").$Enums.RiskLevel;
        dueDate: Date | null;
        completedAt: Date | null;
    }>;
    createTask(createDto: CreateLeasingTaskDto, req: any): Promise<{
        description: string | null;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.TaskStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        category: import(".prisma/client").$Enums.LeasingTaskCategory;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        defaultSLA: number | null;
        riskLevel: import(".prisma/client").$Enums.RiskLevel;
        dueDate: Date | null;
        completedAt: Date | null;
    }>;
    updateTask(id: string, updateDto: UpdateLeasingTaskDto, req: any): Promise<{
        description: string | null;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.TaskStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        category: import(".prisma/client").$Enums.LeasingTaskCategory;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        defaultSLA: number | null;
        riskLevel: import(".prisma/client").$Enums.RiskLevel;
        dueDate: Date | null;
        completedAt: Date | null;
    }>;
    removeTask(id: string, req: any): Promise<{
        success: boolean;
        message: string;
    }>;
    findAllProjects(req: any, filters: any): Promise<({
        tasks: {
            description: string | null;
            title: string;
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.TaskStatus;
            createdAt: Date;
            updatedAt: Date;
            mallId: string | null;
            storeId: string | null;
            assignedToId: string | null;
            leaseId: string | null;
            category: import(".prisma/client").$Enums.LeasingTaskCategory;
            priority: import(".prisma/client").$Enums.TaskPriority;
            franchiseProjectId: string | null;
            defaultSLA: number | null;
            riskLevel: import(".prisma/client").$Enums.RiskLevel;
            dueDate: Date | null;
            completedAt: Date | null;
        }[];
    } & {
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.FranchiseProjectStatus;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        code: string | null;
        brand: string | null;
        concept: string | null;
        storeId: string | null;
        notes: string | null;
        targetRegion: string | null;
        targetCity: string | null;
        targetMallId: string | null;
        storeType: string | null;
        estimatedCapex: number | null;
        estimatedOpex: number | null;
        expectedRevenue: number | null;
        expectedRentCost: number | null;
        feasibilityScore: number | null;
        riskAssessment: string | null;
        projectManagerId: string | null;
        targetOpeningDate: Date | null;
        actualOpeningDate: Date | null;
    })[]>;
    getProjectStatistics(req: any): Promise<{
        total: number;
        pipeline: number;
        evaluation: number;
        approved: number;
        opened: number;
        byCity: {
            city: string;
            count: unknown;
        }[];
        avgFeasibilityScore: number;
    }>;
    findOneProject(id: string, req: any): Promise<{
        tasks: {
            description: string | null;
            title: string;
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.TaskStatus;
            createdAt: Date;
            updatedAt: Date;
            mallId: string | null;
            storeId: string | null;
            assignedToId: string | null;
            leaseId: string | null;
            category: import(".prisma/client").$Enums.LeasingTaskCategory;
            priority: import(".prisma/client").$Enums.TaskPriority;
            franchiseProjectId: string | null;
            defaultSLA: number | null;
            riskLevel: import(".prisma/client").$Enums.RiskLevel;
            dueDate: Date | null;
            completedAt: Date | null;
        }[];
    } & {
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.FranchiseProjectStatus;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        code: string | null;
        brand: string | null;
        concept: string | null;
        storeId: string | null;
        notes: string | null;
        targetRegion: string | null;
        targetCity: string | null;
        targetMallId: string | null;
        storeType: string | null;
        estimatedCapex: number | null;
        estimatedOpex: number | null;
        expectedRevenue: number | null;
        expectedRentCost: number | null;
        feasibilityScore: number | null;
        riskAssessment: string | null;
        projectManagerId: string | null;
        targetOpeningDate: Date | null;
        actualOpeningDate: Date | null;
    }>;
    createProject(createDto: CreateFranchiseProjectDto, req: any): Promise<{
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.FranchiseProjectStatus;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        code: string | null;
        brand: string | null;
        concept: string | null;
        storeId: string | null;
        notes: string | null;
        targetRegion: string | null;
        targetCity: string | null;
        targetMallId: string | null;
        storeType: string | null;
        estimatedCapex: number | null;
        estimatedOpex: number | null;
        expectedRevenue: number | null;
        expectedRentCost: number | null;
        feasibilityScore: number | null;
        riskAssessment: string | null;
        projectManagerId: string | null;
        targetOpeningDate: Date | null;
        actualOpeningDate: Date | null;
    }>;
    updateProject(id: string, updateDto: UpdateFranchiseProjectDto, req: any): Promise<{
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.FranchiseProjectStatus;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        code: string | null;
        brand: string | null;
        concept: string | null;
        storeId: string | null;
        notes: string | null;
        targetRegion: string | null;
        targetCity: string | null;
        targetMallId: string | null;
        storeType: string | null;
        estimatedCapex: number | null;
        estimatedOpex: number | null;
        expectedRevenue: number | null;
        expectedRentCost: number | null;
        feasibilityScore: number | null;
        riskAssessment: string | null;
        projectManagerId: string | null;
        targetOpeningDate: Date | null;
        actualOpeningDate: Date | null;
    }>;
    removeProject(id: string, req: any): Promise<{
        success: boolean;
        message: string;
    }>;
    findAllRequests(req: any, filters: any): Promise<{
        description: string | null;
        type: import(".prisma/client").$Enums.LeasingRequestType;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.RequestStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        createdById: string;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        dueDate: Date | null;
        source: import(".prisma/client").$Enums.RequestSource;
        resolution: string | null;
        resolvedAt: Date | null;
        resolvedById: string | null;
    }[]>;
    getRequestStatistics(req: any): Promise<{
        total: number;
        open: number;
        inProgress: number;
        resolved: number;
        byType: {
            type: string;
            count: unknown;
        }[];
        bySource: {
            source: string;
            count: unknown;
        }[];
        avgResolutionTime: number;
    }>;
    findOneRequest(id: string, req: any): Promise<{
        description: string | null;
        type: import(".prisma/client").$Enums.LeasingRequestType;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.RequestStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        createdById: string;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        dueDate: Date | null;
        source: import(".prisma/client").$Enums.RequestSource;
        resolution: string | null;
        resolvedAt: Date | null;
        resolvedById: string | null;
    }>;
    createRequest(createDto: CreateLeasingRequestDto, req: any): Promise<{
        description: string | null;
        type: import(".prisma/client").$Enums.LeasingRequestType;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.RequestStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        createdById: string;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        dueDate: Date | null;
        source: import(".prisma/client").$Enums.RequestSource;
        resolution: string | null;
        resolvedAt: Date | null;
        resolvedById: string | null;
    }>;
    updateRequest(id: string, updateDto: UpdateLeasingRequestDto, req: any): Promise<{
        description: string | null;
        type: import(".prisma/client").$Enums.LeasingRequestType;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.RequestStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        createdById: string;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        dueDate: Date | null;
        source: import(".prisma/client").$Enums.RequestSource;
        resolution: string | null;
        resolvedAt: Date | null;
        resolvedById: string | null;
    }>;
    resolveRequest(id: string, resolution: string, req: any): Promise<{
        description: string | null;
        type: import(".prisma/client").$Enums.LeasingRequestType;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.RequestStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        createdById: string;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        dueDate: Date | null;
        source: import(".prisma/client").$Enums.RequestSource;
        resolution: string | null;
        resolvedAt: Date | null;
        resolvedById: string | null;
    }>;
    rejectRequest(id: string, reason: string, req: any): Promise<{
        description: string | null;
        type: import(".prisma/client").$Enums.LeasingRequestType;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.RequestStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        createdById: string;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        dueDate: Date | null;
        source: import(".prisma/client").$Enums.RequestSource;
        resolution: string | null;
        resolvedAt: Date | null;
        resolvedById: string | null;
    }>;
    removeRequest(id: string, req: any): Promise<{
        success: boolean;
        message: string;
    }>;
    findAllJobDescriptions(req: any, filters: any): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }[]>;
    getDefaultTemplate(): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        nameTR: string;
        nameEN: string;
        descriptionTR: string | null;
        descriptionEN: string | null;
        coreResponsibilities: string[];
        coreSkills: string[];
        isDefault: boolean;
        isActive: boolean;
    }>;
    findOneJobDescription(id: string, req: any): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }>;
    exportJobDescription(id: string, language: 'TR' | 'EN', req: any): Promise<string>;
    createJobDescription(createDto: CreateJobDescriptionDto, req: any): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }>;
    generateFromTemplate(companyContext: any, req: any): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }>;
    updateJobDescription(id: string, updateDto: Partial<CreateJobDescriptionDto>, req: any): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }>;
    publishJobDescription(id: string, req: any): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }>;
    unpublishJobDescription(id: string, req: any): Promise<{
        tenantId: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        roleNameTR: string;
        roleNameEN: string;
        summaryTR: string | null;
        summaryEN: string | null;
        responsibilitiesTR: string[];
        responsibilitiesEN: string[];
        skillsTR: string[];
        skillsEN: string[];
        sectors: string[];
        seniorityLevel: import(".prisma/client").$Enums.SeniorityLevel;
        companyContext: string | null;
        isTemplate: boolean;
        isPublished: boolean;
        createdById: string;
    }>;
    removeJobDescription(id: string, req: any): Promise<{
        success: boolean;
        message: string;
    }>;
    getDashboardData(req: any): Promise<{
        tasks: {
            total: number;
            pending: number;
            inProgress: number;
            completed: number;
            byCategory: {
                category: string;
                count: unknown;
            }[];
            byPriority: {
                priority: string;
                count: unknown;
            }[];
        };
        projects: {
            total: number;
            pipeline: number;
            evaluation: number;
            approved: number;
            opened: number;
            byCity: {
                city: string;
                count: unknown;
            }[];
            avgFeasibilityScore: number;
        };
        requests: {
            total: number;
            open: number;
            inProgress: number;
            resolved: number;
            byType: {
                type: string;
                count: unknown;
            }[];
            bySource: {
                source: string;
                count: unknown;
            }[];
            avgResolutionTime: number;
        };
    }>;
}
//# sourceMappingURL=leasing-manager.controller.d.ts.map