import { PrismaService } from '../../database/prisma.service';
import { CreateLeasingRequestDto } from './dto/create-leasing-request.dto';
import { UpdateLeasingRequestDto } from './dto/update-leasing-request.dto';
export declare class LeasingRequestsService {
    private prisma;
    constructor(prisma: PrismaService);
    findAll(tenantId: string, filters?: any): Promise<{
        description: string | null;
        type: import(".prisma/client").$Enums.LeasingRequestType;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.RequestStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        createdById: string;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        dueDate: Date | null;
        source: import(".prisma/client").$Enums.RequestSource;
        resolution: string | null;
        resolvedAt: Date | null;
        resolvedById: string | null;
    }[]>;
    findOne(id: string, tenantId: string): Promise<{
        description: string | null;
        type: import(".prisma/client").$Enums.LeasingRequestType;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.RequestStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        createdById: string;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        dueDate: Date | null;
        source: import(".prisma/client").$Enums.RequestSource;
        resolution: string | null;
        resolvedAt: Date | null;
        resolvedById: string | null;
    }>;
    create(tenantId: string, userId: string, createDto: CreateLeasingRequestDto): Promise<{
        description: string | null;
        type: import(".prisma/client").$Enums.LeasingRequestType;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.RequestStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        createdById: string;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        dueDate: Date | null;
        source: import(".prisma/client").$Enums.RequestSource;
        resolution: string | null;
        resolvedAt: Date | null;
        resolvedById: string | null;
    }>;
    update(id: string, tenantId: string, updateDto: UpdateLeasingRequestDto): Promise<{
        description: string | null;
        type: import(".prisma/client").$Enums.LeasingRequestType;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.RequestStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        createdById: string;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        dueDate: Date | null;
        source: import(".prisma/client").$Enums.RequestSource;
        resolution: string | null;
        resolvedAt: Date | null;
        resolvedById: string | null;
    }>;
    resolve(id: string, tenantId: string, userId: string, resolution: string): Promise<{
        description: string | null;
        type: import(".prisma/client").$Enums.LeasingRequestType;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.RequestStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        createdById: string;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        dueDate: Date | null;
        source: import(".prisma/client").$Enums.RequestSource;
        resolution: string | null;
        resolvedAt: Date | null;
        resolvedById: string | null;
    }>;
    reject(id: string, tenantId: string, userId: string, reason: string): Promise<{
        description: string | null;
        type: import(".prisma/client").$Enums.LeasingRequestType;
        title: string;
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.RequestStatus;
        createdAt: Date;
        updatedAt: Date;
        mallId: string | null;
        storeId: string | null;
        assignedToId: string | null;
        leaseId: string | null;
        createdById: string;
        priority: import(".prisma/client").$Enums.TaskPriority;
        franchiseProjectId: string | null;
        dueDate: Date | null;
        source: import(".prisma/client").$Enums.RequestSource;
        resolution: string | null;
        resolvedAt: Date | null;
        resolvedById: string | null;
    }>;
    remove(id: string, tenantId: string): Promise<{
        success: boolean;
        message: string;
    }>;
    getStatistics(tenantId: string): Promise<{
        total: number;
        open: number;
        inProgress: number;
        resolved: number;
        byType: {
            type: string;
            count: unknown;
        }[];
        bySource: {
            source: string;
            count: unknown;
        }[];
        avgResolutionTime: number;
    }>;
    private getRequestsByType;
    private getRequestsBySource;
    private getAvgResolutionTime;
}
//# sourceMappingURL=leasing-requests.service.d.ts.map