import { StoresService } from './stores.service';
import { CreateStoreDto } from './dto/create-store.dto';
import { UpdateStoreDto } from './dto/update-store.dto';
export declare class StoresController {
    private readonly storesService;
    constructor(storesService: StoresService);
    findAll(user: any, filters: any): Promise<({
        mall: {
            type: import(".prisma/client").$Enums.MallType;
            tenantId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            country: string;
            city: string;
            district: string | null;
            address: string;
            managementCompany: string | null;
            relationshipQuality: import(".prisma/client").$Enums.RelationshipQuality;
        };
        leases: {
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.LeaseStatus;
            createdAt: Date;
            updatedAt: Date;
            currency: string;
            mallId: string | null;
            storeId: string;
            assignedToId: string | null;
            contractNumber: string;
            version: number;
            startDate: Date;
            endDate: Date;
            signedDate: Date | null;
            monthlyRent: number;
            escalationType: import(".prisma/client").$Enums.EscalationType;
            escalationRate: number;
            escalationIndex: string | null;
            renewalOptionMonths: number | null;
            renewalNoticeMonths: number;
            commonAreaCharges: number | null;
            securityDeposit: number | null;
            fitOutPeriodDays: number | null;
            documentUrl: string | null;
            documentVersion: number;
        }[];
    } & {
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.StoreStatus;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        code: string;
        brand: string | null;
        concept: string | null;
        country: string;
        city: string;
        district: string | null;
        address: string;
        squareMeters: number;
        openingDate: Date | null;
        mallId: string | null;
        closingDate: Date | null;
    })[]>;
    getStatistics(user: any): Promise<{
        total: number;
        active: number;
        planning: number;
        closed: number;
        byCity: {
            city: string;
            count: unknown;
        }[];
    }>;
    findOne(id: string, user: any): Promise<{
        mall: {
            type: import(".prisma/client").$Enums.MallType;
            tenantId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            country: string;
            city: string;
            district: string | null;
            address: string;
            managementCompany: string | null;
            relationshipQuality: import(".prisma/client").$Enums.RelationshipQuality;
        };
        leases: {
            tenantId: string;
            id: string;
            status: import(".prisma/client").$Enums.LeaseStatus;
            createdAt: Date;
            updatedAt: Date;
            currency: string;
            mallId: string | null;
            storeId: string;
            assignedToId: string | null;
            contractNumber: string;
            version: number;
            startDate: Date;
            endDate: Date;
            signedDate: Date | null;
            monthlyRent: number;
            escalationType: import(".prisma/client").$Enums.EscalationType;
            escalationRate: number;
            escalationIndex: string | null;
            renewalOptionMonths: number | null;
            renewalNoticeMonths: number;
            commonAreaCharges: number | null;
            securityDeposit: number | null;
            fitOutPeriodDays: number | null;
            documentUrl: string | null;
            documentVersion: number;
        }[];
        analytics: {
            tenantId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            storeId: string;
            commonAreaCharges: number | null;
            month: number;
            year: number;
            revenue: number;
            rent: number;
            otherExpenses: number | null;
            rentToRevenueRatio: number;
            revenuePerSquareMeter: number;
            profitMargin: number | null;
            footTraffic: number | null;
            conversionRate: number | null;
            performanceScore: number | null;
            recommendation: import(".prisma/client").$Enums.PerformanceRecommendation | null;
        }[];
    } & {
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.StoreStatus;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        code: string;
        brand: string | null;
        concept: string | null;
        country: string;
        city: string;
        district: string | null;
        address: string;
        squareMeters: number;
        openingDate: Date | null;
        mallId: string | null;
        closingDate: Date | null;
    }>;
    create(user: any, createDto: CreateStoreDto): Promise<{
        mall: {
            type: import(".prisma/client").$Enums.MallType;
            tenantId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            country: string;
            city: string;
            district: string | null;
            address: string;
            managementCompany: string | null;
            relationshipQuality: import(".prisma/client").$Enums.RelationshipQuality;
        };
    } & {
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.StoreStatus;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        code: string;
        brand: string | null;
        concept: string | null;
        country: string;
        city: string;
        district: string | null;
        address: string;
        squareMeters: number;
        openingDate: Date | null;
        mallId: string | null;
        closingDate: Date | null;
    }>;
    update(id: string, user: any, updateDto: UpdateStoreDto): Promise<{
        mall: {
            type: import(".prisma/client").$Enums.MallType;
            tenantId: string;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            country: string;
            city: string;
            district: string | null;
            address: string;
            managementCompany: string | null;
            relationshipQuality: import(".prisma/client").$Enums.RelationshipQuality;
        };
    } & {
        tenantId: string;
        id: string;
        status: import(".prisma/client").$Enums.StoreStatus;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        code: string;
        brand: string | null;
        concept: string | null;
        country: string;
        city: string;
        district: string | null;
        address: string;
        squareMeters: number;
        openingDate: Date | null;
        mallId: string | null;
        closingDate: Date | null;
    }>;
    remove(id: string, user: any): Promise<{
        success: boolean;
        message: string;
    }>;
}
//# sourceMappingURL=stores.controller.d.ts.map